[package]
name = "cairo-sys-rs"
license = "MIT"
authors = ["The gtk-rs Project Developers"]
homepage = "https://gtk-rs.org/"
description = "FFI bindings to libcairo"
version = "0.18.0"
keywords = ["cairo", "ffi", "gtk-rs", "gnome"]
repository = "https://github.com/gtk-rs/gtk-rs-core"
build = "build.rs"
edition = "2021"
rust-version = "1.70"

[lib]
name = "cairo_sys"

[features]
v1_16 = []
v1_18 = ["v1_16"]
png = []
pdf = []
svg = []
ps = []
script = []
win32-surface = []
xlib = ["dep:x11"]
xcb = []
freetype = []
use_glib = ["dep:glib-sys"]

[dependencies]
glib-sys = { workspace = true, optional = true }
libc.workspace = true
x11 = { workspace = true, optional = true, features = ["xlib"] }

[build-dependencies]
cc.workspace = true
