name: Bug Report
description: Something broke or behaves unexpectedly.
labels: [bug, needs:triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please include as much detail as possible so we can reproduce and fix it quickly.
  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-flight
      description: Confirm you have done the basics.
      options:
        - label: I searched existing issues and discussions.
          required: true
        - label: I reproduced this on the latest nightly or main branch.
          required: true
  - type: input
    id: version
    attributes:
      label: Shelldone version
      description: Output of `shelldone -V` (or commit hash if building from source).
      placeholder: 2025.09.26-main
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, window system/compositor, GPU/driver, shell, font if relevant.
      placeholder: Linux 6.11, Wayland (Hyprland), AMD RX 6800 (Mesa 24.2), zsh 5.9
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Exact actions required (commands, config snippets, recordings) to trigger the bug.
      placeholder: |
        1. Start Shelldone with config below
        2. Run command ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened?
      placeholder: The pane should resize without artifacts.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior / logs
      description: Paste console output (`RUST_LOG=debug shelldone ...`), screenshots, etc. Drag & drop files as needed.
      placeholder: Relevant logs, stack traces, screenshots
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Relevant configuration
      description: Minimal `shelldone.lua` snippet or “no config”.
      placeholder: ```lua
return {
  color_scheme = "Tokyo Night",
}
```
  - type: textarea
    id: notes
    attributes:
      label: Additional context
      description: Regression info, bisect results, related issues, or workarounds.
