blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/imagray/Shelldone/discussions
    about: Questions, proposals, and community chat outside of issues.
  - name: Matrix (#shelldone:matrix.org)
    url: https://matrix.to/#/#shelldone:matrix.org
    about: Low-latency chat with maintainers and other contributors.
  - name: Security contact
    url: mailto:team@shelldone.dev
    about: Report vulnerabilities or sensitive issues privately.
