name: windows_tag

on:
  push:
    tags:
      - "20*"

jobs:
  build:
    runs-on: "windows-latest"
    
    env:
      CARGO_INCREMENTAL: "0"
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
      RUSTUP_WINDOWS_PATH_ADD_BIN: "1"

    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable
        with:
          target: "x86_64-pc-windows-msvc"
      - name: "Compile with sccache"
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: "Cache Rust Dependencies"
        uses: actions/cache@v4
        id: cache-cargo-vendor
        with:
          path: |
            vendor
            .cargo/config
          key: "cargo-deps-${{ hashFiles('**/Cargo.lock') }}"
      - name: "Vendor dependecies"
        if: steps.cache-cargo-vendor.outputs.cache-hit != 'true'
        shell: bash
        run: "cargo vendor --locked --versioned-dirs >> .cargo/config"
      - name: "Build shelldone (Release mode)"
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build -p shelldone --release
      - name: "Build shelldone-gui (Release mode)"
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build -p shelldone-gui --release
      - name: "Build shelldone-mux-server (Release mode)"
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build -p shelldone-mux-server --release
      - name: "Build strip-ansi-escapes (Release mode)"
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo build -p strip-ansi-escapes --release
      - name: "Install cargo-nextest from Cargo"
        uses: baptiste0928/cargo-install@v3
        with:
          crate: "cargo-nextest"
          cache-key: "windows"
      - name: "Test"
        shell: cmd
        run: |
          PATH C:\Strawberry\perl\bin;%PATH%
          cargo nextest run --all --no-fail-fast
      - name: "Package"
        shell: bash
        run: "bash ci/deploy.sh"
      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: "windows"
          path: |
            Shelldone-*.zip
            Shelldone-*.exe

  upload:
    runs-on: ubuntu-latest
    needs: build
    if: github.repository == 'shelldone/shelldone'
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4
      - name: "Download artifact"
        uses: actions/download-artifact@v4
        with:
          name: "windows"
      - name: "Checksum"
        shell: bash
        run: "for f in Shelldone-*.zip Shelldone-*.exe ; do sha256sum $f > $f.sha256 ; done"
      - name: "Create pre-release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: "bash ci/retry.sh bash ci/create-release.sh $(ci/tag-name.sh)"
      - name: "Upload to Tagged Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: "bash ci/retry.sh gh release upload --clobber $(ci/tag-name.sh) Shelldone-*.zip Shelldone-*.exe *.sha256"
      - name: "Checkout winget-pkgs"
        uses: actions/checkout@v4
        with:
          repository: "wez/winget-pkgs"
          path: "winget-pkgs"
          token: "${{ secrets.GH_PAT }}"
      - name: "Setup email for winget repo"
        shell: bash
        run: "cd winget-pkgs && git config user.email team@shelldone.dev"
      - name: "Setup name for winget repo"
        shell: bash
        run: "cd winget-pkgs && git config user.name 'Wez Furlong'"
      - name: "Create winget manifest and push to fork"
        shell: bash
        run: "bash ci/make-winget-pr.sh winget-pkgs Shelldone-*.exe"
      - name: "Submit PR"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        shell: bash
        run: 'cd winget-pkgs && gh pr create --fill --body "PR automatically created by release automation in the shelldone repo"'
