name: verify-nightly

on:
  schedule:
    - cron: '0 3 * * *'  # 03:00 UTC nightly
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  verify-ci:
    name: Verify (Nightly CI, Linux)
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          profile: minimal
          override: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest build psutil google-cloud-bigquery grpcio-tools protobuf

      - name: Install k6
        run: |
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Run verify (ci profile)
        env:
          VERIFY_MODE: ci
          NET: '0'
          TIMEOUT_MIN: '60'
          SHELLDONE_PERF_PROFILE: ci
        run: make verify

      - name: Upload verify artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: verify-nightly-artifacts
          path: |
            artifacts/**
            reports/**
